// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBPg_hcBHpHquqM8FKUPWdABFK8RNRRMA',
    appId: '1:703482332279:web:5fc82cb7d693a34b4ef272',
    messagingSenderId: '703482332279',
    projectId: 'movieapp-3cb01',
    authDomain: 'movieapp-3cb01.firebaseapp.com',
    storageBucket: 'movieapp-3cb01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUoaM1C4dKcJnvVtRrBmAhTgYMUVn7d8Y',
    appId: '1:703482332279:android:33922495da9f2f3b4ef272',
    messagingSenderId: '703482332279',
    projectId: 'movieapp-3cb01',
    storageBucket: 'movieapp-3cb01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0zNzSUH-hCt0GjQsH4zcCNH8W_6f3eZw',
    appId: '1:703482332279:ios:00f3fa8f7e3253b84ef272',
    messagingSenderId: '703482332279',
    projectId: 'movieapp-3cb01',
    storageBucket: 'movieapp-3cb01.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0zNzSUH-hCt0GjQsH4zcCNH8W_6f3eZw',
    appId: '1:703482332279:ios:00f3fa8f7e3253b84ef272',
    messagingSenderId: '703482332279',
    projectId: 'movieapp-3cb01',
    storageBucket: 'movieapp-3cb01.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBPg_hcBHpHquqM8FKUPWdABFK8RNRRMA',
    appId: '1:703482332279:web:886538cf832606374ef272',
    messagingSenderId: '703482332279',
    projectId: 'movieapp-3cb01',
    authDomain: 'movieapp-3cb01.firebaseapp.com',
    storageBucket: 'movieapp-3cb01.firebasestorage.app',
  );
}
